server:
  port: 9999
#  entity cluster 配置
spring:
  redis:
    pool:
      max-idle: 100
  thymeleaf:
    cache: false
  mail:
    host: smtp.exmail.qq.com
    username: xxxx
    password: xxxx
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  profiles:
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configLocation: classpath:/mybatis-config.xml
  typeAliasesPackage: org.rediseye.entity

logging:
  level: info
  # ERROR, WARN, INFO, DEBUG or TRACE
  #logging.path=:/home/jar/monitor/log/


